### ISSUE TITLE
404 error after following the instructions

### ISSUE THREAD

**Issue by valk** [watson-developer-cloud/personality-insights-ruby#4]
Hi I followed the exact instructions. Then after inserting the text on localhost:4567, I'm presented with this error:
Internal server error (root cause: text/plain)

The JSON response inside the dev tools is:
{"error":"Internal server error (root cause: text\/plain)","code":404}

Here's the output from the terminal:

 $ ruby app.rb 
endpoint = https://gateway.watsonplatform.net/personality-insights/api/
username = 8856a0b6-4ce1-48c9-b8f7-fda3265dd763
== Sinatra (v1.4.6) has taken the stage on 4567 for development with backup from Thin
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on localhost:4567, CTRL+C to stop
127.0.0.1 - - [15/Aug/2015:22:33:27 +0300] "POST / HTTP/1.1" 200 70 2.2174

**Comment by germanattanasio** [comment]
Thanks @valk, we will look into it.

**Comment by arypbatista** [comment]
Fixed.
Here is my deploy: http://batarypa-personality-insights-ruby.mybluemix.net/
